### ISSUE TITLE
int inside of a record seems to be returned as string instead of number

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-calldata-js#77] opened 2021-10-31 10:00 UTC

**Comment by marc0olo** [comment] 2021-10-31 10:11
are you sure? I think I tested that some time ago and always received `BigInt` as representation for `int`

**Comment by thepiwo** [comment] 2021-10-31 10:14
just noticed using the call-data lib in an existing test setup

![image](https://user-images.githubusercontent.com/6539235/139577823-1c6c9526-c307-49ce-9aca-b3413fbc566d.png)

sure, when its supposed to be like this thats fine for me

**Comment by marc0olo** [comment] 2021-10-31 10:16
so you are referring to the current state of this branch: https://github.com/aeternity/aepp-sdk-js/tree/feature/calldata ?

and using this branch brings you the result on the right whereas in the past you got the result on the left? (screenshot)

**Comment by marc0olo** [comment] 2021-10-31 10:19
I am asking because maybe the SDK does some transformation here. I am pretty sure the calldata lib uses `BigInt` according to the tests I ran few weeks ago

**Comment by dincho** [comment] 2021-11-01 13:08
Please provide minimal reproducible example using the calldata lib public API only. As @marc0olo mentioned this lib works with native BigInts: https://github.com/aeternity/aepp-calldata-js/blob/master/tests/Decoder.js#L307

**Comment by davidyuk** [comment] 2021-11-02 10:17
I had a similar issue in sdk tests, it is probably because `chai` doesn't support BigInt well

**Comment by marc0olo** [comment] 2021-11-02 12:42
@davidyuk but that's an issue of the SDK then, right? then it's related to this again, isn't it? => https://github.com/aeternity/aepp-sdk-js/issues/1290

**Comment by davidyuk** [comment] 2021-11-04 07:36
> but that's an issue of the SDK then, right? 

Nope, sdk doesn't modify BigInts returned from calldata (I planning to keep it as it is), the bug is in `chai` package that probably Philipp uses

**Comment by marc0olo** [comment] 2021-11-04 07:57
@thepiwo did you use `chai` ? can you confirm and close the issue?

**Closed** 2021-11-04 08:35 UTC
Labels: invalid, component/decoder
